services:
- type: web
  name: wikijs
  runtime: image
  image:
    url: ghcr.io/requarks/wiki:2
  plan: standard
  autoDeploy: false
  envVars:
  - key: DB_TYPE
    value: postgres
  - key: DB_HOST
    fromDatabase:
      name: wikijs-postgres
      property: host
  - key: DB_PORT
    fromDatabase:
      name: wikijs-postgres
      property: port
  - key: DB_NAME
    fromDatabase:
      name: wikijs-postgres
      property: database
  - key: DB_USER
    fromDatabase:
      name: wikijs-postgres
      property: user
  - key: DB_PASS
    fromDatabase:
      name: wikijs-postgres
      property: password


