services:
- type: web
  name: wordpress
  env: docker
  plan: standard
  autoDeploy: false
  disk:
    name: config
    mountPath: /var/www/html
    sizeGB: 20
  envVars:
  - key: WORDPRESS_DB_HOST
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Hostname
  - key: WORDPRESS_DB_NAME
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Database
  - key: WORDPRESS_DB_USER
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Username
  - key: WORDPRESS_DB_PASSWORD
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Password

