services:
- type: web
  name: wiki
  env: docker
  plan: standard
  autoDeploy: false
  envVars:
  - key: DB_TYPE
    value: postgres
  - key: DB_HOST
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Hostname
  - key: DB_PORT
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Port
  - key: DB_NAME
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Database
  - key: DB_USER
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Username
  - key: DB_PASS
    fromDatabase:
      name: fujinninja-wordpress-postgres
      property: Password

